#!/bin/bash

# -v verbose
# -s silent
# -H header
# -A user agent

user_agent='Mozilla/5.0 (X11; Linux x86_64; rv:147.0; ffff) Gecko/20100101 Firefox/147.0'

prefix='https://www.allaboutcircuits.com'
dir='./01.DC'

cd ${dir}

# sleep 2; echo '002'; curl -s -o 002.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-1/static-electricity/"
# sleep 3; echo '003'; curl -s -o 003.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-1/conductors-insulators-electron-flow/"
# sleep 2; echo '004'; curl -s -o 004.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-1/electric-circuits/"
# sleep 5; echo '005'; curl -s -o 005.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-1/voltage-current/"
# sleep 1; echo '006'; curl -s -o 006.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-1/resistance/"
# sleep 3; echo '007'; curl -s -o 007.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-1/voltage-current-practical-circuit/"
# sleep 5; echo '008'; curl -s -o 008.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-1/conventional-versus-electron-flow/"
# sleep 4; echo '010'; curl -s -o 010.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-2/voltage-current-resistance-relate/"
# sleep 4; echo '011'; curl -s -o 011.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-2/analogy-ohms-law/"
# sleep 3; echo '012'; curl -s -o 012.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-2/power-electric-circuits/"
# sleep 4; echo '013'; curl -s -o 013.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-2/calculating-electric-power/"
# sleep 1; echo '014'; curl -s -o 014.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-2/resistors/"
# sleep 6; echo '015'; curl -s -o 015.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-2/nonlinear-conduction/"
# sleep 2; echo '016'; curl -s -o 016.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-2/circuit-wiring/"
# sleep 2; echo '017'; curl -s -o 017.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-2/polarity-voltage-drops/"
# sleep 2; echo '018'; curl -s -o 018.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-2/computer-simulation-electric-circuits/"
# sleep 2; echo '020'; curl -s -o 020.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/importance-electrical-safety/"
# sleep 6; echo '021'; curl -s -o 021.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/physiological-effects-electricity/"
# sleep 3; echo '022'; curl -s -o 022.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/shock-current-path/"
# sleep 6; echo '023'; curl -s -o 023.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/ohms-law-again/"
# sleep 1; echo '024'; curl -s -o 024.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/safe-practices/"
# sleep 1; echo '025'; curl -s -o 025.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/emergency-response/"
# sleep 5; echo '026'; curl -s -o 026.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/common-sources-hazard/"
# sleep 2; echo '027'; curl -s -o 027.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/safe-circuit-design/"
# sleep 5; echo '028'; curl -s -o 028.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/safe-meter-usage/"
# sleep 6; echo '029'; curl -s -o 029.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-3/electric-shock-data/"
# sleep 6; echo '031'; curl -s -o 031.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-4/scientific-notation/"
# sleep 4; echo '032'; curl -s -o 032.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-4/arithmetic-scientific-notation/"
# sleep 4; echo '033'; curl -s -o 033.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-4/metric-notation/"
# sleep 1; echo '034'; curl -s -o 034.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-4/metric-prefix-conversions/"
# sleep 3; echo '035'; curl -s -o 035.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-4/hand-calculator-use/"
# sleep 2; echo '036'; curl -s -o 036.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-4/scientific-notation-in-spice/"
# sleep 3; echo '038'; curl -s -o 038.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/what-are-series-and-parallel-circuits/"
# sleep 5; echo '039'; curl -s -o 039.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/simple-series-circuits/"
# sleep 4; echo '040'; curl -s -o 040.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/simple-parallel-circuits/"
# sleep 4; echo '041'; curl -s -o 041.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/solving-series-and-parallel-circuits-with-the-table-method-and-ohms-law/"
# sleep 1; echo '042'; curl -s -o 042.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/conductance/"
# sleep 2; echo '043'; curl -s -o 043.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/power-calculations/"
# sleep 2; echo '044'; curl -s -o 044.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/correct-use-of-ohms-law/"
# sleep 3; echo '045'; curl -s -o 045.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/spice-simulation-of-series-and-parallel-circuits/"
# sleep 3; echo '046'; curl -s -o 046.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/component-failure-analysis/"
# sleep 1; echo '047'; curl -s -o 047.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-5/building-simple-resistor-circuits/"
# sleep 4; echo '049'; curl -s -o 049.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-6/voltage-divider-circuits/"
# sleep 1; echo '050'; curl -s -o 050.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-6/kirchhoffs-voltage-law-kvl/"
# sleep 3; echo '051'; curl -s -o 051.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-6/current-divider-circuits/"
# sleep 2; echo '052'; curl -s -o 052.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-6/kirchhoffs-current-law-kcl/"
# sleep 5; echo '054'; curl -s -o 054.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-7/what-is-a-series-parallel-circuit/"
# sleep 5; echo '055'; curl -s -o 055.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-7/analysis-technique/"
# sleep 6; echo '056'; curl -s -o 056.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-7/re-drawing-complex-schematics/"
# sleep 5; echo '057'; curl -s -o 057.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-7/component-failure-analysis-2/"
# sleep 1; echo '058'; curl -s -o 058.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-7/series-parallel-resistor-circuits/"
# sleep 6; echo '060'; curl -s -o 060.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/what-is-a-meter/"
# sleep 2; echo '061'; curl -s -o 061.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/voltmeter-design/"
# sleep 3; echo '062'; curl -s -o 062.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/voltmeter-impact-measured-circuit/"
# sleep 6; echo '063'; curl -s -o 063.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/ammeter-design/"
# sleep 3; echo '064'; curl -s -o 064.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/ammeter-impact-measured-circuit/"
# sleep 6; echo '065'; curl -s -o 065.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/ohmmeter-design/"
# sleep 6; echo '066'; curl -s -o 066.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/high-voltage-ohmmeters/"
# sleep 5; echo '067'; curl -s -o 067.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/multimeters/"
# sleep 4; echo '068'; curl -s -o 068.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/kelvin-resistance-measurement/"
# sleep 3; echo '069'; curl -s -o 069.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/bridge-circuits/"
# sleep 5; echo '070'; curl -s -o 070.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/wattmeter-design/"
# sleep 4; echo '071'; curl -s -o 071.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-8/custom-calibration-resistances/"
# sleep 1; echo '073'; curl -s -o 073.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-9/analog-and-digital-signals/"
# sleep 1; echo '074'; curl -s -o 074.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-9/voltage-signal-systems/"
# sleep 5; echo '075'; curl -s -o 075.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-9/current-signal-systems/"
# sleep 1; echo '076'; curl -s -o 076.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-9/tachogenerators/"
# sleep 5; echo '077'; curl -s -o 077.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-9/thermocouples/"
# sleep 1; echo '078'; curl -s -o 078.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-9/ph-measurement/"
# sleep 1; echo '079'; curl -s -o 079.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-9/strain-gauges/"
# sleep 2; echo '081'; curl -s -o 081.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/what-is-network-analysis/"
# sleep 5; echo '082'; curl -s -o 082.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/branch-current-method/"
# sleep 6; echo '083'; curl -s -o 083.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/mesh-current-method/"
# sleep 4; echo '084'; curl -s -o 084.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/solving-unbalanced-wheatstone-bridge-circuits-via-mesh-current-method/"
# sleep 4; echo '085'; curl -s -o 085.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/node-voltage-method/"
# sleep 3; echo '086'; curl -s -o 086.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/introduction-network-theorems/"
# sleep 4; echo '087'; curl -s -o 087.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/millmans-theorem/"
# sleep 1; echo '088'; curl -s -o 088.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/superposition-theorem/"
# sleep 4; echo '089'; curl -s -o 089.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/thevenins-theorem/"
# sleep 3; echo '090'; curl -s -o 090.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/nortons-theorem/"
# sleep 3; echo '091'; curl -s -o 091.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/thevenin-norton-equivalencies/"
# sleep 4; echo '092'; curl -s -o 092.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/millmans-theorem-revisited/"
# sleep 1; echo '093'; curl -s -o 093.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/maximum-power-transfer-theorem/"
# sleep 2; echo '094'; curl -s -o 094.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-10/delta-y-and-y-conversions/"
# sleep 4; echo '096'; curl -s -o 096.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-11/electron-activity-chemical-reactions/"
# sleep 5; echo '097'; curl -s -o 097.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-11/battery-construction/"
# sleep 1; echo '098'; curl -s -o 098.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-11/battery-ratings/"
# sleep 4; echo '099'; curl -s -o 099.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-11/special-purpose-batteries/"
# sleep 1; echo '100'; curl -s -o 100.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-11/practical-considerations-batteries/"
# sleep 4; echo '102'; curl -s -o 102.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-12/introduction-conductance-and-conductors/"
# sleep 2; echo '103'; curl -s -o 103.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-12/conductor-size/"
# sleep 1; echo '104'; curl -s -o 104.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-12/conductor-ampacity/"
# sleep 5; echo '105'; curl -s -o 105.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-12/fuses/"
# sleep 6; echo '106'; curl -s -o 106.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-12/specific-resistance/"
# sleep 4; echo '107'; curl -s -o 107.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-12/temperature-coefficient-resistance/"
# sleep 1; echo '108'; curl -s -o 108.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-12/superconductivity/"
# sleep 3; echo '109'; curl -s -o 109.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-12/insulator-breakdown-voltage/"
# sleep 3; echo '111'; curl -s -o 111.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-13/electric-fields-capacitance/"
# sleep 3; echo '112'; curl -s -o 112.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-13/capacitors-and-calculus/"
# sleep 3; echo '113'; curl -s -o 113.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-13/factors-affecting-capacitance/"
# sleep 1; echo '114'; curl -s -o 114.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-13/series-and-parallel-capacitors/"
# sleep 3; echo '115'; curl -s -o 115.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-13/practical-considerations-capacitors/"
# sleep 2; echo '117'; curl -s -o 117.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-14/permanent-magnets/"
# sleep 1; echo '118'; curl -s -o 118.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-14/electromagnetism/"
# sleep 3; echo '119'; curl -s -o 119.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-14/magnetic-units-of-measurement/"
# sleep 5; echo '120'; curl -s -o 120.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-14/permeability-and-saturation/"
# sleep 5; echo '121'; curl -s -o 121.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-14/electromagnetic-induction/"
# sleep 3; echo '122'; curl -s -o 122.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-14/mutual-inductance/"
# sleep 4; echo '124'; curl -s -o 124.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-15/magnetic-fields-and-inductance/"
# sleep 1; echo '125'; curl -s -o 125.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-15/inductors-and-calculus/"
# sleep 6; echo '126'; curl -s -o 126.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-15/factors-affecting-inductance/"
# sleep 4; echo '127'; curl -s -o 127.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-15/series-and-parallel-inductors/"
# sleep 6; echo '128'; curl -s -o 128.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-15/practical-considerations-inductors/"
# sleep 3; echo '130'; curl -s -o 130.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-16/electrical-transients/"
# sleep 6; echo '131'; curl -s -o 131.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-16/capacitor-transient-response/"
# sleep 2; echo '132'; curl -s -o 132.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-16/inductor-transient-response/"
# sleep 5; echo '133'; curl -s -o 133.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-16/voltage-current-calculations/"
# sleep 5; echo '134'; curl -s -o 134.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-16/why-l-r-and-not-lr/"
# sleep 4; echo '135'; curl -s -o 135.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-16/complex-voltage-and-current-calculations/"
# sleep 4; echo '136'; curl -s -o 136.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-16/complex-circuits/"
# sleep 4; echo '137'; curl -s -o 137.html -A "${user_agent}" "${prefix}/textbook/direct-current/chpt-16/solving-for-unknown-time/"
